<?php

return [
    'guard' => 'api',

    'permissions' => [
        'users.view',
        'users.create',
        'users.update',
        'users.delete',
        'roles.view',
        'companies.view',
        'companies.create',
        'companies.update',
        'companies.delete',
        'companies.settings.view',
        'companies.settings.update',

        'accounts.view',
        'accounts.create',
        'accounts.update',
        'accounts.activate',
        'accounts.deactivate',
        'accounts.delete',

        'journals.view',
        'journals.create',
        'journals.update',
        'journals.delete',
        'journals.post',

        'accounting.periods.view',
        'accounting.periods.create',
        'accounting.periods.update',
        'accounting.periods.close',

        'accounting.ledger.view',

        // Phase 5
        'customers.view',
        'customers.create',
        'customers.update',
        'customers.deactivate',
        'suppliers.view',
        'suppliers.create',
        'suppliers.update',
        'suppliers.deactivate',
        'sales.invoices.view',
        'sales.invoices.create',
        'sales.invoices.update',
        'sales.invoices.post',
        'sales.invoices.delete',
        'purchases.bills.view',
        'purchases.bills.create',
        'purchases.bills.update',
        'purchases.bills.post',
        'purchases.bills.delete',
        'customer.receipts.view',
        'customer.receipts.create',
        'customer.receipts.update',
        'customer.receipts.post',
        'customer.receipts.delete',
        'supplier.payments.view',
        'supplier.payments.create',
        'supplier.payments.update',
        'supplier.payments.post',
        'supplier.payments.delete',

        'accounting.reports.view',
    ],

    'roles' => [
        'Admin' => ['*'],

        'Accountant' => [
            'users.view',
            'companies.view',
            'accounts.view',
            'accounts.create',
            'accounts.update',
            'accounts.deactivate',
            'accounts.activate',
            'journals.view',
            'journals.create',
            'journals.update',
            'journals.delete',
            'journals.post',
            'accounting.periods.view',
            'accounting.periods.create',
            'accounting.periods.update',
            'accounting.ledger.view',
            'customers.view',
            'customers.create',
            'customers.update',
            'customers.deactivate',
            'suppliers.view',
            'suppliers.create',
            'suppliers.update',
            'suppliers.deactivate',
            'sales.invoices.view',
            'sales.invoices.create',
            'sales.invoices.update',
            'sales.invoices.post',
            'sales.invoices.delete',
            'purchases.bills.view',
            'purchases.bills.create',
            'purchases.bills.update',
            'purchases.bills.post',
            'purchases.bills.delete',
            'customer.receipts.view',
            'customer.receipts.create',
            'customer.receipts.update',
            'customer.receipts.post',
            'customer.receipts.delete',
            'supplier.payments.view',
            'supplier.payments.create',
            'supplier.payments.update',
            'supplier.payments.post',
            'supplier.payments.delete',
            'accounting.reports.view',
        ],

        'Manager' => [
            'users.view',
            'companies.view',
            'companies.update',
            'companies.settings.view',
            'companies.settings.update',
            'accounts.view',
            'journals.view',
            'accounting.periods.view',
            'accounting.ledger.view',
            'customers.view',
            'suppliers.view',
            'sales.invoices.view',
            'purchases.bills.view',
            'customer.receipts.view',
            'supplier.payments.view',
            'accounting.reports.view',
        ],

        'Staff' => [
            'companies.view',
        ],
    ],
];
